Update the sudo PAM file too

diff --git a/dirlock.install b/dirlock.install
--- a/dirlock.install
+++ b/dirlock.install
@@ -1,29 +1,27 @@
-post_install() {
-    local pamfile=/etc/pam.d/system-auth
+update_pam() {
+    local pamfile="$1"
+    local group="$2"
 
-    local authjump=$(sed -En '/^-?auth.*success=[0-9]/{s|.*success=([0-9]).*|\1|;p}' \
+    local value=$(sed -En "/^-?${group}.*success=[0-9]/{s|.*success=([0-9]).*|\1|;p}" \
                    "$pamfile" | sort -nr | head -n 1)
 
-    local passjump=$(sed -En '/^-?password.*success=[0-9]/{s|.*success=([0-9]).*|\1|;p}' \
-                   "$pamfile" | sort -nr | head -n 1)
-
-    if [ -z "$authjump" ] || [ -z "$passjump" ]; then
-        echo "WARNING: could not update $pamfile - you need to enable the dirlock PAM module manually" >&2
+    if [ -z "$value" ]; then
+        echo "WARNING: could not update $group entry in $pamfile - you need to enable the dirlock PAM module manually" >&2
         return
     fi
 
-    local authnext=$(($authjump + 1))
-    local passnext=$(($passjump + 1))
+    local next=$(($value + 1))
 
     sed -f - -i "$pamfile" <<-EOF
-	/^-\?auth.*success=$authjump/ {
+	/^-\?$group.*success=$value/ {
 		i\
-		auth       [success=$authnext user_unknown=ignore default=die]   /var/lib/dirlock/pam_dirlock.so
-	}
-
-	/^-\?password.*success=$passjump/ {
-		i\
-		password   [success=$passnext user_unknown=ignore default=die]   /var/lib/dirlock/pam_dirlock.so
+		$group       [success=$next user_unknown=ignore default=die]   /var/lib/dirlock/pam_dirlock.so
 	}
 	EOF
+}
+
+post_install() {
+    update_pam /etc/pam.d/system-auth auth
+    update_pam /etc/pam.d/system-auth password
+    update_pam /etc/pam.d/sudo auth
 }
